- name: Create VPC
  ec2_vpc_net:
    cidr_block: "{{ vpc_cidr_block }}"
    name: "{{ vpc_name }}"
    region: "{{ aws_region }}"
    state: present
  register: created_vpc

- debug: var=created_vpc

- name: Empty vars/vpc_role_vars file
  file:
    path: aws/vars/vpc_role_vars
    state: absent

- name: Verify vars/vpc_role_vars file exists
  file:
    path: vars/vpc_role_vars
    state: touch
  changed_when: false

- name: Register VPC info
  lineinfile:
    dest: vars/vpc_role_vars
    line: "role_vpc_id: {{ created_vpc.vpc.id }}"
    state: present
    regexp: "^role_vpc_id:*"
